#不过滤的配置文件
filter:
  unFilterList: #不过滤路径
    - "/"
    - "/doc.html"
    - "/**/*.js"
    - "/**/*.css"
    - "/**/*.html"
    - "/**/*.svg"
    - "/**/*.pdf"
    - "/**/*.jpg"
    - "/**/*.png"
    - "/**/*.ico"
    - "/**/*.ttf"
    - "/**/*.woff"
    - "/User/Login"
    - "/Cas/IsLogin"
    - "/Cas/VerifyTicket"
  filterList: #过滤路径
    - "/**" # /** 匹配本路径且包含子路径, /*
  debugUnFilterList: # 调试时不过滤路径
    - "/swagger-resources/**"
    - "/v2/**"
  debug: true # 是否调试
  setUrl: false # 是否设置下面3个参数
  loginUrl: "" #登录地址 需配到unFilterList
  successUrl: "" #成功地址 -
  noAuthorityUrl: "" #无权限地址 -